FROM node:13.8.0-alpine3.11

EXPOSE 8443

RUN apk --update add git less openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

RUN mkdir -p /app && \
    cd /app && \
    git clone https://gitlab.com/babiaxr/open-easyrtc.git

WORKDIR /app/open-easyrtc
RUN npm install

WORKDIR /app/open-easyrtc/server_example
RUN mkdir customcerts
RUN npm install

CMD [ "node", "server_ssl_customcerts.js" ]