---
  version: "2.1"
  services:
    sslbabiartc-server:
      image: babiaxr/easyrtc:sslautosigned
      container_name: sslbabiartc
      ports:
        - 8443:8443
      restart: unless-stopped
  volumes:
    certsbabia:
      external: true