---
  version: "2.1"
  services:
    babiartc-server:
      image: babiaxr/easyrtc:nonssl
      container_name: babiartc
      ports:
        - 8080:8080
      restart: unless-stopped
  volumes:
    certsbabia:
      external: true