version: "3.1"

services:
  easyrtc-server:
    image: babiaxr/easyrtc:sslautosigned
    container_name: easyrtc-server
    build:
      context: .
      args:
        EASYRTC_BRANCH: "master"
    command: server_ssl
    volumes:
      - ./certs:/usr/src/app/certs:ro
    networks:
      - frontend
    ports:
      - "8443:8443"
    tty: true
    stdin_open: true
    volumes:
      - ./static:/static:ro

networks:
  frontend:
  backend:
